version: '3.7'
services:
  app:
    build: .
    environment:
      - LANG=C.UTF-8
    ports:
      - 11026:3000
    stdin_open: true
    tty: true
    volumes:
      - .:/opt/oniwa
      - /opt/oniwa/node_modules
